# Generated by Django 2.2.3 on 2019-08-27 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190826_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='lang',
            field=models.CharField(blank=True, max_length=50, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 11, 43, 47, 679615, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
