# Generated by Django 2.2.3 on 2019-09-02 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20190829_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 4, 13, 5, 54, 677786, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
