# Generated by Django 2.2.3 on 2019-09-16 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20190902_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 18, 16, 36, 57, 910004, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
